@echo off

echo +ssyhho::-----:/++osssshhyo++yhhyysoyhyyhhso/+:://osooo/+++osso+/+oyssssssssooo+/++syosyyydho++ooso/
echo //+//:-:///+oo+oosyhdmmdmmddmmNNmmmmdddhyyoo++oyyhhhdmmdhso+ooso+o++++oo++////::oooshyyyssyys+///-:/
echo s++:+syddhhyyhhyhddmmmNNmmNNmddmmmdmmdysyhhysyddddhhysyssssooo+/shyyysssssyhyss+o++++sssssss+//shddd
echo ddddddmNNmmmdmmddmmmmmNNNNNNNNNmmmddmNmdmmddmmyoymmhyhhhhhhyyhyyssyddys++o/-:+so+/+/+ss+/oyhyshhyddd
echo mmmmmmNNNNNNNmmmmNNNNNNNNNNNNNNNNNNNNNNNNNmmmNmdddyhmmmdysyyyhddhhyo/::-:+:///+++++:oyhhhhyshhhmmmNN
echo NmNNNNNNNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNmmNNNmmdhhhddmmmmmdyso+oo+/:-./syhho+oo+///shyyyhyss++sdddm
echo NNNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmNNmhysssyyysssyhdmmmmdyss+/+++yddddddhso//oso++++/+shdhhh
echo NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmhsyyyyssssyyyyysssyyhdmmmhhhyyys+o+++/smNmdo//+/:::-syyy::+
echo NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNssyhyyyyyyyyyyyyyyyhhhyyhmmmhyhmddddmmNNNNNNmy+/:--oyhs+oys
echo NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmhyhyyysysyssssysyyyhhhhhhhhdmhyhmddmmdhyhdmmmNNmyo//yyyys+oy
echo NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNdhhssooooo+osssssysssyhhhhhhhyyyhhdmNNmmyo/::/oshmdhshmds+/:::
echo NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNh/+o+++++/oo+oooo+ssssosysyhddhhhhys+oyyso+oyyyysooyyyydmmdddds:
echo NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmhso/::-::--:::::////++oos+sssyyhhhhhyyso+yysoyhmdhysssyyhhsshmNNNNNm
echo NNNNNNNNNNNNNNNNNNNNNdo////////:::////////:::::::/:/oyhyyyoyhoyyyysssyymNNNNNNmNNmmhoooo+oooosyhhhyy
echo NNNNNNNNNNNNNNNNNNNNNNy///oho+++//++++++++++//:///+++++oydmddyssssooooooyhdNNNNNNNNNNNmdy+/ohhyssooo
echo NNNNNNNNNNNNNNNNNNNMNNNdooo++o+///+ooooooo++++ossoooooso++/ooossssysyysysoosshmNNNNNNNNNmy+oshhdhmNN
echo NNNNNNNNNMNMMMMNNMMMMNNNNhyyso+oo++ssosooo+oosssssssyssssssssysosyhhhyhhddddhhsshmNNNNNNNNmysyoossyh
echo MMMMMNNNMMNMMMMNNMMNNNNNNNmhssssso++ooossssssssyyyyyyyyyysysyyssyyhhhhhddmNNNNNmdhydNNNNNNNNso+/+sdN
echo NNMMMMMMMMMMMMMMMNMNNNNMNMNNmyyyyyso++ooo++ooosyyyyyyhhyssyyhhhhhddddmmNNMMMMMMNMNNhNMNNMNNNmy:-oyhy
echo MMMMMMMMMMMMMMMMMNNNNMMMMMMNNNhyyyysssssooosssssyyyyhhyysshhdddddddmmmNNMMMMMMMMMNNmmNNNNNNNNddyys+/
echo MMMMMMMMMMMMMMMMNNNMMMMMMMMNMMMmdhyhhyyysssyyyyyhhddmmNNmhhhdddddmddmmNNMMMMMMMMMMMNNNNNNNNNNNho+///
echo MMMMMMMMMMMMMNNNMMMMMMMMMMMMMMMMMMNNmmdhhhhhdddddmmNMMMMMNdhddddddddmNNNMMMMMMMMMNNMMNNNmNNNNNmmdmmh
echo MMMMMMMMMMMMMNNNMMMMMMMMMMMMMMMMMMMMMMMNmmdddhhhhhhdmNMMMMNmddddddmmNNMMMMMMMMMMMMMNNNNNNNNNNNNNNNNN
echo NNNNMNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNmNNMMMMMMMMNmdhddmmNNMMMMMMMMMMNNNNMNNNNNNNNNNNMMNN
echo MNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmddhddmmNNNMNMMMMNmNNNNNMNNMNNNNNNNMN
echo MMMMNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNmmmdddddmmdmdNNMNNMMMMMMMMMNNNMM
echo MMMMMNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMNNNNMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo NNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

pause